// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgrftxifqwppaniradyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhncmZ0eGlmcXdwcGFuaXJhZHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODg3OTgsImV4cCI6MjA2MjI2NDc5OH0.EiXaaaLitk_wTojTEUs-dVx9fkz6dewohp_J8SJd8BY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);